name: Deploy and Update SSM Parameters

on:
  push:
    branches: [ main ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      
      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
          
      - name: Update SSM Parameters
        run: |
          aws ssm put-parameter --name "/api-3000/DATABASE_URL" --value "${{ secrets.DATABASE_URL }}" --type "SecureString" --overwrite
          aws ssm put-parameter --name "/api-3000/JWT_SECRET_KEY" --value "${{ secrets.JWT_SECRET_KEY }}" --type "SecureString" --overwrite